# Generated by Django 5.2.7 on 2025-10-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_alter_debate_creator_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
